name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Linting (@atsevofni/web)
        run: pnpm lint:web

      - name: Check (server)
        run: pnpm check:server --fix

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Format (@atsevofni/web)
        run: pnpm format:web --fix

      - name: Format (server)
        run: pnpm format:server --fix
