name: Check
on: push
jobs:
  format-and-lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-uv-dependencies

      - name: Format (server)
        run: cd apps/server && uv run ruff format

      - name: Check (server)
        run: cd apps/server && uv run ruff check --fix

  format-and-lint-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Lint (@atsevofni/web)
        run: pnpm lint:web --fix .

      - name: Format (@atsevofni/web)
        run: pnpm format:web --fix .
